// Path: C:\ProgramasGodMode\DGM-MAT-Mobile\web\app.js
const RENDEZVOUS="https://dgm-mat-rendezvous.vercel.app/api/public-discovery?node=PC-Vazao-Anjos";
const STORAGE="dgm-mat-mobile-state-v1";
const state=JSON.parse(localStorage.getItem(STORAGE)||"{}");
state.threads=Array.isArray(state.threads)?state.threads:[];state.activeId=state.activeId||null;state.apiBase=state.apiBase||"";state.pending=Array.isArray(state.pending)?state.pending:[];
const el={drawer:document.getElementById("drawer"),list:document.getElementById("threadList"),chat:document.getElementById("chat"),input:document.getElementById("input"),dot:document.getElementById("dot"),connection:document.getElementById("connectionText"),title:document.getElementById("titleButton"),context:document.getElementById("contextLine"),intent:document.getElementById("intentBar"),dialog:document.getElementById("renameDialog"),renameInput:document.getElementById("renameInput"),endpoint:document.getElementById("endpointLabel")};
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]})}
function api(path,opt){opt=opt||{};opt.headers=Object.assign({"Content-Type":"application/json"},opt.headers||{});return fetch(state.apiBase+path,opt)}
function online(ok,msg){el.dot.classList.toggle("online",ok);el.connection.textContent=msg}
async function discover(){if(location.hostname.includes("tail")||location.hostname.match(/^100\./)||location.hostname==="localhost"||location.hostname==="127.0.0.1"){state.apiBase="";save();return true}try{const r=await fetch(RENDEZVOUS,{cache:"no-store"});if(!r.ok)throw Error(r.status);const d=await r.json();if(d.endpoint){state.apiBase=d.endpoint.replace(/\/$/,"");save();return true}}catch(e){}return Boolean(state.apiBase)}
async function connect(){await discover();try{const r=await api("/mobile/status");if(!r.ok)throw Error(r.status);const d=await r.json();online(true,"PC ligado · DGM-MAT pronto");el.endpoint.textContent=d.tailscale&&d.tailscale.hostname||"PC";return true}catch(e){online(false,"PC indisponível · modo offline");return false}}
function active(){return state.threads.find(function(t){return t.id===state.activeId})||null}
function renderThreads(){el.list.innerHTML=state.threads.map(function(t){return '<button class="thread '+(t.id===state.activeId?"active":"")+'" data-id="'+esc(t.id)+'"><span class="thread-title">'+esc(t.title||"Nova conversa")+'</span><span class="thread-meta">'+new Date(t.updated_at||Date.now()).toLocaleString("pt-PT",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})+'</span></button>'}).join("")}
function renderChat(){const t=active();el.title.textContent=t&&t.title||"Nova conversa";el.context.textContent=t&&t.repository?(t.repository+(t.project?" · "+t.project:"")):"DGM-MAT · conversa contínua";el.chat.innerHTML=(t&&t.messages||[]).map(function(m){return '<div class="message-row '+(m.role==="user"?"user":"")+'"><div class="message '+(m.role==="user"?"user":"assistant")+' '+(m.state==="pending"?"pending":"")+'">'+esc(m.content)+'<div class="meta">'+(m.role==="user"?"Tu":"DGM-MAT")+" · "+new Date(m.created_at||Date.now()).toLocaleTimeString("pt-PT",{hour:"2-digit",minute:"2-digit"})+(m.state==="pending"?" · pendente":"")+"</div></div></div>"}).join("");el.chat.scrollTop=el.chat.scrollHeight;renderThreads()}
function localThread(){const t={id:"local-"+crypto.randomUUID(),title:"Nova conversa",created_at:new Date().toISOString(),updated_at:new Date().toISOString(),messages:[],status:"active"};state.threads.unshift(t);state.activeId=t.id;save();renderChat();return t}
async function createServer(title){const r=await api("/mobile/threads",{method:"POST",body:JSON.stringify({title:title||"Nova conversa"})});if(!r.ok)throw Error(r.status);return r.json()}
async function serverThread(t){if(!t.id.startsWith("local-"))return t;const s=await createServer(t.title);const i=state.threads.findIndex(function(x){return x.id===t.id});if(i>=0){state.threads[i]=s;state.activeId=s.id}save();return s}
async function load(){if(!(await connect())){if(!state.threads.length)localThread();renderChat();return}try{const r=await api("/mobile/threads");if(!r.ok)throw Error(r.status);const d=await r.json();state.threads=d.threads||[];if(!state.activeId||!state.threads.some(function(t){return t.id===state.activeId}))state.activeId=state.threads[0]&&state.threads[0].id||null;if(!state.activeId){const t=await createServer();state.threads=[t];state.activeId=t.id}save();renderChat();await flush()}catch(e){if(!state.threads.length)localThread();renderChat()}}
async function select(id){state.activeId=id;save();const t=active();if(t&&!t.id.startsWith("local-")&&await connect())try{const r=await api("/mobile/threads/"+encodeURIComponent(id));if(r.ok){const s=await r.json(),i=state.threads.findIndex(function(x){return x.id===id});if(i>=0)state.threads[i]=s;save()}}catch(e){}renderChat();el.drawer.classList.remove("open")}
function showIntent(i){if(!i){el.intent.classList.add("hidden");return}el.intent.classList.remove("hidden");const labels={chat:"conversa",status:"estado",audit:"auditoria",repair:"reparação",implement:"implementação",sync:"sincronização",research:"investigação",memory:"memória",deploy:"publicação"};el.intent.innerHTML="<strong>Entendido como "+esc(labels[i.intent]||i.intent)+"</strong> · confiança "+Math.round((i.confidence||0)*100)+"%"+(i.requires_approval?" · aprovação necessária":"")}
async function send(){const value=el.input.value.trim();if(!value)return;let t=active()||localThread();const pending={id:"pending-"+crypto.randomUUID(),role:"user",content:value,created_at:new Date().toISOString(),state:"pending"};t.messages.push(pending);t.updated_at=pending.created_at;el.input.value="";save();renderChat();if(!(await connect())){state.pending.push({threadId:t.id,content:value});save();return}try{t=await serverThread(t);const r=await api("/mobile/threads/"+encodeURIComponent(t.id)+"/messages",{method:"POST",body:JSON.stringify({content:value})});if(!r.ok)throw Error(r.status);const d=await r.json(),i=state.threads.findIndex(function(x){return x.id===t.id});if(i>=0)state.threads[i]=d.thread;save();renderChat();showIntent(d.intent)}catch(e){state.pending.push({threadId:t.id,content:value});save();online(false,"PC indisponível · mensagem guardada")}}
async function flush(){if(!(await connect()))return;for(const item of state.pending.slice()){try{let t=state.threads.find(function(x){return x.id===item.threadId});if(!t)continue;t=await serverThread(t);const r=await api("/mobile/threads/"+encodeURIComponent(t.id)+"/messages",{method:"POST",body:JSON.stringify({content:item.content})});if(!r.ok)throw Error(r.status);const d=await r.json(),i=state.threads.findIndex(function(x){return x.id===t.id});if(i>=0)state.threads[i]=d.thread;state.pending=state.pending.filter(function(x){return x!==item});save();showIntent(d.intent)}catch(e){break}}renderChat()}
async function rename(){const t=active();if(!t)return;el.renameInput.value=t.title||"Nova conversa";el.dialog.showModal()}
document.getElementById("saveRename").addEventListener("click",async function(e){e.preventDefault();const title=el.renameInput.value.trim(),t=active();if(!title||!t)return;if(t.id.startsWith("local-"))t.title=title;else if(await connect()){const r=await api("/mobile/threads/"+encodeURIComponent(t.id)+"/rename",{method:"POST",body:JSON.stringify({title:title})});if(r.ok){const s=await r.json(),i=state.threads.findIndex(function(x){return x.id===t.id});if(i>=0)state.threads[i]=s}}save();renderChat();el.dialog.close()});
document.getElementById("newChat").onclick=function(){localThread();el.drawer.classList.remove("open")};document.getElementById("openDrawer").onclick=function(){el.drawer.classList.add("open")};document.getElementById("closeDrawer").onclick=function(){el.drawer.classList.remove("open")};document.getElementById("renameButton").onclick=rename;el.title.onclick=rename;document.getElementById("refresh").onclick=load;el.list.onclick=function(e){const b=e.target.closest("[data-id]");if(b)select(b.dataset.id)};document.getElementById("composer").onsubmit=function(e){e.preventDefault();send()};el.input.addEventListener("input",function(){el.input.style.height="auto";el.input.style.height=Math.min(el.input.scrollHeight,160)+"px"});el.input.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});window.addEventListener("online",flush);if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(function(){});load();setInterval(function(){if(!document.hidden)flush()},15000);
